// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260509160414_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ContactNumber")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Candidates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactNumber = "+381601234567",
                            DateOfBirth = new DateOnly(2000, 1, 1),
                            Email = "anne.smith@gmail.com",
                            Name = "Anne Smith"
                        },
                        new
                        {
                            Id = 2,
                            ContactNumber = "+381601234568",
                            DateOfBirth = new DateOnly(1998, 3, 15),
                            Email = "john.peterson@gmail.com",
                            Name = "John Peterson"
                        },
                        new
                        {
                            Id = 3,
                            ContactNumber = "+381601234569",
                            DateOfBirth = new DateOnly(1997, 7, 22),
                            Email = "emily.johnson@gmail.com",
                            Name = "Emily Johnson"
                        },
                        new
                        {
                            Id = 4,
                            ContactNumber = "+381601234570",
                            DateOfBirth = new DateOnly(1995, 11, 5),
                            Email = "michael.brown@gmail.com",
                            Name = "Michael Brown"
                        },
                        new
                        {
                            Id = 5,
                            ContactNumber = "+381601234571",
                            DateOfBirth = new DateOnly(2001, 2, 10),
                            Email = "sophia.davis@gmail.com",
                            Name = "Sophia Davis"
                        },
                        new
                        {
                            Id = 6,
                            ContactNumber = "+381601234572",
                            DateOfBirth = new DateOnly(1996, 9, 18),
                            Email = "daniel.wilson@gmail.com",
                            Name = "Daniel Wilson"
                        },
                        new
                        {
                            Id = 7,
                            ContactNumber = "+381601234573",
                            DateOfBirth = new DateOnly(1999, 12, 3),
                            Email = "olivia.martinez@gmail.com",
                            Name = "Olivia Martinez"
                        },
                        new
                        {
                            Id = 8,
                            ContactNumber = "+381601234574",
                            DateOfBirth = new DateOnly(1994, 6, 27),
                            Email = "james.anderson@gmail.com",
                            Name = "James Anderson"
                        },
                        new
                        {
                            Id = 9,
                            ContactNumber = "+381601234575",
                            DateOfBirth = new DateOnly(2002, 4, 14),
                            Email = "emma.thomas@gmail.com",
                            Name = "Emma Thomas"
                        },
                        new
                        {
                            Id = 10,
                            ContactNumber = "+381601234576",
                            DateOfBirth = new DateOnly(1993, 8, 30),
                            Email = "william.taylor@gmail.com",
                            Name = "William Taylor"
                        });
                });

            modelBuilder.Entity("Domain.Models.CandidateSkill", b =>
                {
                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("CandidateId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("CandidateSkills", (string)null);

                    b.HasData(
                        new
                        {
                            CandidateId = 1,
                            SkillId = 1
                        },
                        new
                        {
                            CandidateId = 1,
                            SkillId = 5
                        },
                        new
                        {
                            CandidateId = 1,
                            SkillId = 12
                        },
                        new
                        {
                            CandidateId = 1,
                            SkillId = 18
                        },
                        new
                        {
                            CandidateId = 2,
                            SkillId = 2
                        },
                        new
                        {
                            CandidateId = 2,
                            SkillId = 5
                        },
                        new
                        {
                            CandidateId = 2,
                            SkillId = 17
                        },
                        new
                        {
                            CandidateId = 2,
                            SkillId = 20
                        },
                        new
                        {
                            CandidateId = 3,
                            SkillId = 3
                        },
                        new
                        {
                            CandidateId = 3,
                            SkillId = 7
                        },
                        new
                        {
                            CandidateId = 3,
                            SkillId = 19
                        },
                        new
                        {
                            CandidateId = 4,
                            SkillId = 4
                        },
                        new
                        {
                            CandidateId = 4,
                            SkillId = 11
                        },
                        new
                        {
                            CandidateId = 4,
                            SkillId = 18
                        },
                        new
                        {
                            CandidateId = 5,
                            SkillId = 1
                        },
                        new
                        {
                            CandidateId = 5,
                            SkillId = 6
                        },
                        new
                        {
                            CandidateId = 5,
                            SkillId = 12
                        },
                        new
                        {
                            CandidateId = 6,
                            SkillId = 13
                        },
                        new
                        {
                            CandidateId = 6,
                            SkillId = 14
                        },
                        new
                        {
                            CandidateId = 6,
                            SkillId = 18
                        },
                        new
                        {
                            CandidateId = 7,
                            SkillId = 8
                        },
                        new
                        {
                            CandidateId = 7,
                            SkillId = 9
                        },
                        new
                        {
                            CandidateId = 7,
                            SkillId = 17
                        },
                        new
                        {
                            CandidateId = 8,
                            SkillId = 15
                        },
                        new
                        {
                            CandidateId = 8,
                            SkillId = 19
                        },
                        new
                        {
                            CandidateId = 8,
                            SkillId = 20
                        },
                        new
                        {
                            CandidateId = 9,
                            SkillId = 16
                        },
                        new
                        {
                            CandidateId = 9,
                            SkillId = 5
                        },
                        new
                        {
                            CandidateId = 9,
                            SkillId = 18
                        },
                        new
                        {
                            CandidateId = 10,
                            SkillId = 1
                        },
                        new
                        {
                            CandidateId = 10,
                            SkillId = 11
                        },
                        new
                        {
                            CandidateId = 10,
                            SkillId = 12
                        },
                        new
                        {
                            CandidateId = 10,
                            SkillId = 19
                        });
                });

            modelBuilder.Entity("Domain.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Skills", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "C# programming"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Java programming"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Python"
                        },
                        new
                        {
                            Id = 4,
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = 5,
                            Name = "SQL"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Database design"
                        },
                        new
                        {
                            Id = 7,
                            Name = "NoSQL databases"
                        },
                        new
                        {
                            Id = 8,
                            Name = "English"
                        },
                        new
                        {
                            Id = 9,
                            Name = "German"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Russian"
                        },
                        new
                        {
                            Id = 11,
                            Name = "React"
                        },
                        new
                        {
                            Id = 12,
                            Name = ".NET"
                        },
                        new
                        {
                            Id = 13,
                            Name = "C programming"
                        },
                        new
                        {
                            Id = 14,
                            Name = "C++ programming"
                        },
                        new
                        {
                            Id = 15,
                            Name = "DevOps"
                        },
                        new
                        {
                            Id = 16,
                            Name = "PHP"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Jira"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Git"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Docker"
                        },
                        new
                        {
                            Id = 20,
                            Name = "AWS"
                        });
                });

            modelBuilder.Entity("Domain.Models.CandidateSkill", b =>
                {
                    b.HasOne("Domain.Models.Candidate", "Candidate")
                        .WithMany("CandidateSkills")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Skill", "Skill")
                        .WithMany("CandidateSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Domain.Models.Candidate", b =>
                {
                    b.Navigation("CandidateSkills");
                });

            modelBuilder.Entity("Domain.Models.Skill", b =>
                {
                    b.Navigation("CandidateSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
